export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FALIURE = "FETCH_POST_FALIURE";
export const POST_UPDATED = "POST_UPDATED";